// Shared enums mirroring the Prisma schema. Kept in sync manually so the
// frontend and AI service can consume them without a Prisma dependency.

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  STAFF = 'STAFF',
  AUDITOR = 'AUDITOR',
  MERCHANT = 'MERCHANT',
  BENEFICIARY = 'BENEFICIARY',
}

export enum OrganizationType {
  GOVERNMENT = 'GOVERNMENT',
  NGO = 'NGO',
  UNIVERSITY = 'UNIVERSITY',
  FOUNDATION = 'FOUNDATION',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
}

export enum ProgramType {
  SCHOLARSHIP = 'SCHOLARSHIP',
  MEDICAL = 'MEDICAL',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
  LIVELIHOOD = 'LIVELIHOOD',
  SENIOR_CITIZEN = 'SENIOR_CITIZEN',
  PWD = 'PWD',
  EMERGENCY_CASH = 'EMERGENCY_CASH',
  EDUCATION_VOUCHER = 'EDUCATION_VOUCHER',
  FARMER_SUBSIDY = 'FARMER_SUBSIDY',
  CASH_FOR_WORK = 'CASH_FOR_WORK',
}

export enum ProgramStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSED = 'DISBURSED',
  CANCELLED = 'CANCELLED',
}

export enum TransactionType {
  DISBURSEMENT = 'DISBURSEMENT',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  TRANSFER = 'TRANSFER',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum MerchantCategory {
  GROCERY = 'GROCERY',
  PHARMACY = 'PHARMACY',
  RESTAURANT = 'RESTAURANT',
  RETAIL = 'RETAIL',
  EDUCATION = 'EDUCATION',
  HEALTHCARE = 'HEALTHCARE',
  TRANSPORTATION = 'TRANSPORTATION',
  OTHER = 'OTHER',
}

export enum MerchantStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum AnalysisType {
  DUPLICATE_DETECTION = 'DUPLICATE_DETECTION',
  FRAUD_DETECTION = 'FRAUD_DETECTION',
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  ANOMALY_DETECTION = 'ANOMALY_DETECTION',
  ELIGIBILITY_PREDICTION = 'ELIGIBILITY_PREDICTION',
}

export enum AnalysisResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
}
